# Generated by Django 4.2.15 on 2024-10-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tg_name",
        ),
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telegram Chat ID"
            ),
        ),
    ]
