# Generated by Django 4.2.15 on 2024-10-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_tg_name_user_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ник в Telegram"
            ),
        ),
    ]
