# Generated by Django 4.2.15 on 2024-10-06 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_tg_name"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
