# Generated by Django 4.2.15 on 2024-10-03 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={},
        ),
    ]
