# Generated by Django 4.2.15 on 2024-10-03 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0003_alter_habit_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
    ]
